### ISSUE TITLE
Stream.filter() does nothing

### ISSUE THREAD

**Issue by roblav96** [dmvaldman/samsara#15]
Not sure if I'm doing this correctly here, but:
```javascript
this.xAccu = new Accumulator( 0, {
	min: -this.width,
	max: this.width
} )
this.xAccu.subscribe( this.input.pluck( 'delta' ) )
this.xAccu.filter( function () {
	return this.touching == true
}.bind( this ) )
```

I tried returning false and true to see if it did anything but it doesn't.

**Comment by dmvaldman** [comment]
Could I see the entire file? Using `.filter` or any of the other methods returns a new stream. So you would write

```
this.filteredXAccum = this.xAccu.filter( function () {
    return this.touching == true
}.bind( this ) )
```

then use `this.filteredXAccum` somewhere.

**Comment by roblav96** [comment]
Ohhh OK that's why. haha I thought it would overwrite the current stream.

I don't have much yet, still toying around with it.
```javascript
module.exports = View.extend( {

	initialize: function () {

		this.wWidth = window.innerWidth
		this.wHeight = window.innerHeight

		this.width = this.wWidth * 0.15
		this.height = 49
		this.temp = [ {}, {}, {}, {}, {}, {} ]

		this.surfs = []
		this.layout = new SequentialLayout( {
			direction: 0
		} )

		this.input = new TouchInput( {
			direction: TouchInput.DIRECTION.X,
			scale: 1.5
		} )

		var i, len = this.temp.length
		for ( i = 0; i < len; i++ ) {
			this.surfs[ i ] = new _SURF( {
				index: i,
				width: this.width,
				height: this.height
			} )
			this.input.subscribe( this.surfs[ i ].surf )
		}
		this.layout.addItems( this.surfs )

		this.touching = false
		this.x = new Transitionable( 0 )
		this.xDiff = new Differential()
		this.xDiff.subscribe( this.x )
		this.xAccu = new Accumulator( 0, {
			min: -this.width,
			max: this.width
		} )
		this.xAccu.subscribe( this.input.pluck( 'delta' ) )
		this.xAccu.subscribe( this.xDiff )
		this.xAccu.filter( function () {
			return this.touching == true
		}.bind( this ) )

		this.input.on( 'start', function ( pay ) {
			this.x.reset()
			this.touching = true
		}.bind( this ) )

		this.input.on( 'end', function ( pay ) {
			this.touching = false
			this.centerIt()
		}.bind( this ) )

		this.xAccu.on( 'update', function ( pay ) {
			console.log( 'this.touching >', this.touching )
			if ( this.touching == false ) {
				return
			}
			console.log( 'pay >', pay )
		}.bind( this ) )

		this.add( {
			align: [ 0, 1 ],
			transform: Transform.translate( [ -this.width * 0.5, 0 ] )
		} ).add( {
			transform: this.xAccu.map( function ( v ) {
				var value = v
				return Transform.translateX( value )
			} )
		} ).add( this.layout )

	},

	centerIt: function ( now ) {
		this.x.halt()
		this.x.reset( this.xAccu.get() )
		this.x.set( 0, {
			duration: 250,
			curve: Curves.outBack
		} )
	}
})
```

**Comment by roblav96** [comment]
I'm trying to follow your safari tabs example

**Comment by roblav96** [comment]
I didn't mean to close this, sorry!

**Comment by dmvaldman** [comment]
Let me know if this solves your problem. If solved I'll close the issue.

`filter` does need to be improved, because it won't automatically send the appropriate event channels. For instance it should send an `end` event if it has been receiving updates that suddenly got filtered out. Then it should send a `start` event once it activates again. Currently it doesn't do any of this, so some bugs may occur.

**Comment by dmvaldman** [comment]
Looking at some of your code, you may want to experiment with using size primitives. Samsara was made so you would never need to write `window.innerHeight`, etc, and it's made to be responsive so that sizes adjust if the window is resized, or the mobile device rotated, etc.

Take a look at http://samsarajs.org/docs/#render-tree-nodes, all the values for `size`, `proportions`, `margins`, and `aspectRatio` can be used in `Surfaces` and `Views`. So for instance, instead of defining your `_Surf` class to have a `size = [.15 * window.innerWidth, 49]`, you can define it with

```
proportions : [.15, false]
size : [false, 49]
```

`false` here means "override with some other defined value". Now the size will resize with the window, and your view doesn't need to know about what its containing size is. If its containing size is the window's size it will be 15% the width of the window. If its containing size is something else (say it's inside a View that's inside a Scrollview that's inside...etc) it will be 15% the width of whatever that is.

**Comment by roblav96** [comment]
Good points here. I completely forgot all about using true and false for sizes XD

I've modified my little sandbox project to work fine without the filter. I like things as minimal as possible. Thank you!!!

**Comment by dmvaldman** [comment]
I'd like to close this issue as I believe it's resolved in 0.2.0. Let me know if you're still having problems

**Comment by dmvaldman** [comment]
Closing. Happy to reopen if the problem persists.

**Comment by roblav96** [comment]
This can be closed yes. Thank you!
