### ISSUE TITLE
Size value semantics

### ISSUE THREAD

**Issue by culyun** [dmvaldman/samsara#33]
Hi David,

Please consider deprecating the use of undefined, true, and false in Size options.  Why not simply define numerical constants for the special values and export them from an appropriate namespace in the core?

eg.

  export const parent = -1; 
  export const dom = -2;
  export const ignore = -3; 

eg. use

  var fred = new Surface({
     size : [Size.parent, 42]
   });

------------

This is superior to my mind as:

1. There's no guessing what undefined etc. actually means
2. They use the same underlying storage type (Number), which may help the browser optimize things a little
3. They are way easier to grep

**Comment by dmvaldman** [comment]
I've thought about this, and opted for the albeit confusing `true`, `false`, `undefined` paradigm, but am open to suggestions. Where do you think `Size` should be? Should it be a module you import in with a bunch of constants? What about specifying `false` in `proportions`?

**Comment by daKmoR** [comment]
I would vote for that as well... 

how about keep them them where they are need? e.g. define them in SizeNode.js directly so there is no need to import some other file?

and for `false` in `proportions` from a quick glance I don't see what it does? nor can I guess? so also a strong indicator to use a constant with a better name?

**Comment by dmvaldman** [comment]
I'd like SizeNode to not be a public facing module, so can't put it there. Putting `false` in proportions (or in size) just means "ignore". It makes doing something like:

```js
{
    size : [false, 100],
    proportions : [.5, false]
}
```

work, since an "ignored" dimension is filled by a well-defined dimension.

In a future version, you'll be able to pass a function into the size, like so

```js
{
    size : function(parentSize){
        return [.5*parentSize[0], 100]
    }
}
```

Then I could consider getting rid of this confusing `true`, `false`, `undefined` business, and give developers something more powerful anyway.

**Comment by daKmoR** [comment]
thx for the explanation :)
So size is "like" pixels and proportions is like "align/origin" if I got that right :p and using one means you have to have a false at the other...

The function approach sounds really neat. However I guess it should still be possible to easily set parent, dom, ignore Size without using a function every time?

How about putting them in SizeNodePublic.js? and SizeNode just requires it?

**Comment by culyun** [comment]
Hi guys,

@daKmoR I like your SizeNodePublic.js idea, just not the name.  I suggest bundling all "special values" (both public and private) in a single module, importing that module into the public facing SamsaraEssentials.js (choose a better name) and re-exporting only those values intended for public consumption.

------------

Regarding the goodness of false, true, undefined.  I'm sorry, but for me they are surprising.  By that I mean when I see them in use, they cause a me to stop in my tracks.  I have to think what they mean.  They communicate intention to the size algebra, but they don't communicate anything to me!

@dmvaldman, Is there something special about proportions that would prevent the use of negative constants to define "ignored"?

----------

Also, I had a look at the compose function in size.js. I think it could be optimized a little.

Since spec.proportions trumps spec.size, why perform the spec.size calculations when spec also has proportions??  Are they intended to be mutually exclusive?  
  
Lastly I want believe that `if (spec['size'] !== undefined)` is faster than `if (spec.size)` since no coercion is required, but I think I'm clutching at straws.

**Comment by dmvaldman** [comment]
Proportions and size can both be provided, so you have to check for both. For instance

```
{
    proportions : [false, .5],
    size : [100, false]
}
```

**Comment by culyun** [comment]
@dmvaldman

Thanks for sticking with this discussion.  Here's a few random mockups  to ponder..

Ditch "proportions" property, but allow proportional size fields

{
    size : [100, 0.5]
}

Deprecate true, false, and undefined (yeah I know I sound like a scratchy record)

{
    size : [Size.Dom, 0.5] // where eg. Size.Dom = -1
}

{
    size : [100, Size.Parent] // where eg. Size.Parent = -2
}

Add generalizations and specializations ala HTML styles

{
    proportions : 0.5, // equivalent to proportions : [0.5, 0.5]
}

{
    size_y : 100, // equivalent to size : [false, 100]
}

**Comment by dmvaldman** [comment]
I think the syntax I would prefer is something like

```
    {
        size : function(parentSize){
             return [50, parentSize[1]];
        }
    }
```

Then we wouldn't need any of: `aspectRatio`, `proportions`, `margins` (but maybe we would keep some for convenience, like `proportions`). We would still need something for `true` sizing though, which could be to return `undefined` or some other non-numeric quantity as a width or height.

**Comment by culyun** [comment]
I like the look of this.

I take it that your not keen on using negative numbers for named constants to replace true.  I hope that  makes sense..

Would there be any performance impact using non-numeric quantities??

**Comment by dmvaldman** [comment]
It's not a performance problem that's the concern. It's the burden of requiring in another module like `Size` everywhere you need to use parental size information (which is common). 

By using a function we can also use one single generic concept instead of the myriad that is `aspectRatio`, `margins`, `proportions`, and `undefined` and `false` values.

**Comment by culyun** [comment]
You've sold me :-)  Looking forward to the changes!!

**Comment by dmvaldman** [comment]
As of 6d127d9, `size` values can now accept functions. The argument to the function is the parent node's size. For example:

```
size : function (parentSize) {
    return [100, .5 * parentSize[1]]
}
```

is equivalent to

```
size : [100, false],
proportions : [false, .5]
```

Note now you can do even more complicated logic. Say you wanted the size to be the largest square that fits the parent:

```
size : function (parentSize) {
    var length = Math.min(parentSize[0], parentSize[1]);
    return [length, length]
}
```

Since functions can also return `true` as a width or height or both to defer sizing to the DOM calculated size.

Keep in mind, that though arbitrary state can be put into the size function, the size function will only be executed when a parent's size is changed. Hence it only makes sense to make the size depend on the parent's size, and not any other state.

I'll be updating some of the demos to reflect this change. Everything is still backwards compatible, but we may deprecate some things in the future (like `aspectRatio`, `false` and `undefined`).
