### ISSUE TITLE
MouseInput.on('update', ...) sometimes gets offsetX & offsetY wrong?

### ISSUE THREAD

**Issue by daKmoR** [dmvaldman/samsara#37]
See my example here with open console:
http://codepen.io/anon/pen/grbNmN?editors=0010

every time `event.offsetX === event.clientX ` there will a console log.

just drag the surface wildly around.

_Test in latest Chrome (Version 48.0.2564.116)_

**Comment by dmvaldman** [comment]
Ah, yes this is a bug caused when the mouse moves so fast that it actually moves beyond the element. Internally Samsara removes the `mousemove` listener from the `surface` to the `window` in order to keep the `mousemove` events coming, but when the listener is on the `window` the `offsetX` is relative to the `window` and not the `surface`.

I'm honestly not quite sure how to fix this at the moment. What are you using the `offsetX`, or `clientX` properties for?

**Comment by daKmoR** [comment]
I see... I guess that it is not easily fixed...

I did use it for calculate the bounding box of the dragged element for drag and drop as `clientX - offsetX = top left corner`.
But it is much more reliant to use
```
surface._layout.on('update', function(layoutInfo) {
	var position = Transform.getTranslate(layoutInfo.transform),
		size = surface.getSize();
```
anyway.

So we can just close this or keep it as a reminder that some super magic would be nice here :p

**Comment by dmvaldman** [comment]
Yeah, the latter approach is the way to go

**Comment by daKmoR** [comment]
sure :)

**Comment by dmvaldman** [comment]
As of 4441ab80f057f9f55fc06558b5eb14835b0eac77 Inputs no longer emit `offsetX`, `offsetY`, `clientX`, or `clientY` data. They now emit the original DOM event in the `event` key, from which the user can manually query `event.offsetX` for instance. 

For this issue, you can also access the event's target in `event.target` and `event.currentTarget` (which changes during event bubbling) to calculate the correct `offsetX/Y`.
