### ISSUE TITLE
Working with the right streaming API

### ISSUE THREAD

**Issue by HighOnDrive** [dmvaldman/samsara#5]
Samsara looks like an interesting idea whose time has certainly come. Over at Cycle.js.org we are making all our interfaces with streams, it's completely natural and very powerful. We use RxJS which gives us tremendous reactive streaming power. 

How do you see Samsara fitting into the future of reactive UI's now that all the main frameworks are now on the RxJS bandwagon? I can see Samsara working very well with Cycle.js, where we are exploring the potential of building UI's and interactions with streams.

**Comment by dmvaldman** [comment]
Great question. I'm encouraged by all the stream-based programming I've been seeing of late as well. However, most of the work leveraged RxJS/Bacon.js for handling application state. The beginning example may be incrementing a counter, which is a perfect reflection of this.

What I'm trying to do with Samsara is different in that it is completely agnostic about application state. It only cares about presentation state: height, width, position, orientation, etc. This is something I haven't seen people doing with reactive programming, but I think it's a part of application development that could benefit a lot from reactive principles. Especially because animation is by its nature continuous, and streams/signals are a great way of thinking about data that changes continuously. In this way, a closer comparison to Samsara is Elm.

I think it will be relatively straightforward to integrate Samsara with other choices of frameworks that do data-binding (React, Backbone, Cycle, etc). Samsara moves around rectangles, and those libraries fill them with content. That's my vision, at least. I'll be putting forth effort into making examples of such integrations soon.

Would love to hear more of your thoughts.
