### ISSUE TITLE
[Question] Min & Max Opacity

### ISSUE THREAD

**Issue by jd-carroll** [dmvaldman/samsara#51]
Within the `_DOMOutput.js` controller the following is set as the min & max opacity:

```
var MIN_OPACITY = 0.0001;
var MAX_OPACITY = 0.9999;
```

Is the purpose of this to enable the click through associated with `style.visibility: hidden`?

**Comment by dmvaldman** [comment]
Actually the point of this code is to keep the DOM element in an accelerated layer. There were bugs in browsers that would demote the layer (take it out of GPU memory) if opacity was 0 or 1. These may have been fixed. It's worth testing by toggling "see painted rectangles" in chrome/safari

For click-through, opacity 0 layers still absorb clicks, though visibility hidden layers don't. Unfortunately toggling visibility triggers a paint. I've tried only toggling pointer-events (for the same effect) but there are some bugs in chrome :-(

**Comment by trusktr** [comment]
Also note, if you switch to nested DOM (using preserve-3d), then this will cause your elements to always be flattened in the case you ever adopt having non-leaf renderables.

It makes sense to use neste DOM and preserve-3d because then (if you only care about DOM rendering and not necessarily WebGL), then you can completely rely on the HTML/CSS engine to cache transforms and multiply them. All Samsara would have to do is pass the matrix3d values for each element in the tree, and the HTML/CSS engine does the rest. This is advantageous because then we don't have to continually set the `style` attribute for all elements, which means a performance gain since the HTML/CSS engine can use the internal cached numerical values.

**Comment by dmvaldman** [comment]
Samsara does make use of nested DOM using a `ContainerSurface`, like Famo.us did. As you say, this allows the DOM to do the matrix math for you and results in a single style update if all you're changing is the container. For the case of opacity, what we'll be doing is if you set the opacity of a `ContainerSurface`, we'll just migrate that to its children (recursively if necessary).

**Comment by trusktr** [comment]
> Samsara does make use of nested DOM using a ContainerSurface, like Famo.us did.

The container surface in Famo.us 0.3 and below creates a *new* 3D context, which is different than nesting elements using preserve-3d and having them render in the *same* 3D context as their parent.

If you set the opacity of a ContainerSurface in Famo.us 0.3, it will make everything in it transparent, and since it's content will already be flattened before (due to overflow:hidden for clipping) then opacity flattening has no impact here. *The whole 3D scene inside of the container surface will simply be transparent*.

If you look at my site, http://trusktr.io, you'll see the container surface in use. In the menu on the left, click the "clobe" example, then after the clobe example is loaded, open and close the left menu. What you will see happen is that the 3D scene with the rotating cube is flattened inside of the surface that contains the cube's scene. Likewise, if we were to apply opacity to it, it will simply make the entire 3D container transparent.

What I've just described is already possible to do without having the new opacity changes. The new opacity changes simply *prevent us from having 3D opacity*, because now what happens in a scene with preserve-3d is that the element that has opacity applied to it *becomes a new 3D context and all it's children becomes part of the new context*, which is not necessarily what we want.

Here is a 3D scene using plain HTML/CSS (but is exactly how my engine renders things using nested DOM): https://jsfiddle.net/trusktr/ymonmo70/1

Now, if we apply opacity to the root element of the car, with intent to make the entire car transparent, look what happens (try it out in Chrome, Firefox, and Safari): https://jsfiddle.net/trusktr/ymonmo70/2

Now, I have a challenge for you: open up the [first fiddle](https://jsfiddle.net/trusktr/ymonmo70/1) and make the whole car transparent using CSS `opacity` without flattening.

What you'll realize, and what you've suggested in the other thread, is to apply opacity to the leafs. You'll be able to do it successfully in that example.

Now, here's the real problem. In the following fiddle, there is a red box: https://jsfiddle.net/trusktr/ymonmo70/4. I challenge you to make the red box (and all of it's children) transparent using the CSS `opacity` property. Your goal is to consider the red box and everything in it as a single object, the root of a 3D object in a scene graph.

You won't be able to do it without flattening the car and without restructuring the HTML elements into a more non-nested structure.

Or, have I simply overlooked how to do it?

**Comment by trusktr** [comment]
Here is a 3D scene using plain HTML/CSS (but is exactly how my engine renders things using nested DOM): https://jsfiddle.net/trusktr/ymonmo70/1

Now, if we apply opacity to the root element of the car, with intent to make the entire car transparent, look what happens (try it out in Chrome, Firefox, and Safari): https://jsfiddle.net/trusktr/ymonmo70/2

Now, I have a challenge for you: open up the [first fiddle](https://jsfiddle.net/trusktr/ymonmo70/1) and make the whole car transparent using CSS `opacity` without flattening.

What you'll realize, and what you've suggested in the other thread, is to apply opacity to the leafs. You'll be able to do it successfully in that example.

Now, here's the real problem. In the following fiddle, there is a red box: https://jsfiddle.net/trusktr/ymonmo70/4. I challenge you to make the red box (and all of it's children) transparent using the CSS `opacity` property. Your goal is to consider the red box and everything in it as a single object, the root of a 3D object in a scene graph.

You won't be able to do it without flattening the car and without restructuring the HTML elements into a more non-nested structure.

Or, have I simply overlooked how to do it?

**Comment by aprender** [comment]
Hi gents,

Do we all agree that the W3C spec is broken?

If we agree, then I'm thinking we submit an amendment for review.

**Comment by dmvaldman** [comment]
@trusktr To make the red border transparent, you would need to add a new `<div>` as a child of the `car` and create a border around it. Then you could set the opacity of the `<div>` without flattening the scene. 

I see your point, however. This spec change implies that HTML tags that have children have to choose between:

1. having some visual style (like a border, or containing `TextNodes`)
2. having a 3D context
3. having opacity < 1

Where you can only choose two. (And having (2) + (3) means the library must also pass the opacity down to the leaves).

**Comment by trusktr** [comment]
> @trusktr To make the red border transparent, you would need to add a new <div> as a child of the car and create a border around it. Then you could set the opacity of the <div> without flattening the scene.

@dmvaldman Exactly! This means we must change the HTML markup rather than simply apply CSS styling, which defeats the purpose of CSS itself. We should be able to achieve the desired visual effect by writing *only* CSS without modifying (i.e. without access to) the original markup.

@aprender I agree. I got your email, and would be down to discuss how to change the spec on Skype. I added you!
